# Generated by Django 2.1.4 on 2019-09-11 17:23

from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('application', models.CharField(choices=[(messenger.models.AccountType('Twitter'), 'Twitter'), (messenger.models.AccountType('Telegram'), 'Telegram')], max_length=20)),
                ('company_property', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=40)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Account')),
            ],
        ),
    ]
