# Generated by Django 2.1.4 on 2019-09-16 11:09

from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=5000)),
                ('type', models.CharField(choices=[(messenger.models.EventType('Tweet'), 'Tweet'), (messenger.models.EventType('Message'), 'Message')], max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=5000)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Account')),
            ],
        ),
    ]
