# Generated by Django 2.1.4 on 2019-09-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=5000)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Account')),
            ],
        ),
    ]
