# Generated by Django 2.1.4 on 2019-09-11 22:20

from django.db import migrations, models
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[(messenger.models.MessageType('Tweet'), 'Tweet'), (messenger.models.MessageType('Message'), 'Message')], default='Tweet', max_length=20),
            preserve_default=False,
        ),
    ]
